services:
  postgraphile:
    container_name: postgraphile
    image: graphile/postgraphile
    depends_on:
      - postgres
    env_file:
      - ./.env
    ports:
      - "5433:5433"
    networks:
      - database
    command:
      [
        "--connection", "${DATABASE_URL:-postgres://admin:secret@postgres_container:5432/postgres}", 
        "--port", "5433", 
        "--schema", "public", 
        "--enhance-graphiql"
      ]

networks:
  database: